# Generated by Django 4.2.15 on 2025-10-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='location',
        ),
        migrations.RemoveField(
            model_name='blooddonationrequest',
            name='approved',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
